---
- name: apt_repository ~> add ubuntu certbot ppa
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version != '20'

- name: apt_repository ~> add stretch backports
  apt_repository:
    repo: deb http://deb.debian.org/debian stretch-backports main
    state: present
  when: ansible_distribution_major_version == '9'

- name: apt_repository ~> add buster-backports
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
  when: ansible_distribution_major_version == '10'
